repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        language: system
        entry: make format
        types: [python]
        stages: [commit, push]
    -   id: lint
        name: lint
        language: system
        entry: make lint
        types: [python]
        stages: [commit, push]
    -   id: test
        name: test
        language: system
        entry: make test
        types: [python]
        stages: [push]
        
